# Generated by Django 2.0.5 on 2018-05-25 00:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 25, 0, 28, 43, 483384, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 25, 0, 28, 43, 521440, tzinfo=utc)),
        ),
    ]
