# Generated by Django 2.0.5 on 2018-05-25 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180525_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(),
        ),
    ]
