# Generated by Django 2.0.5 on 2018-05-25 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20180525_0543'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPatent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patent_id', models.CharField(max_length=255)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.News')),
            ],
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
